### ISSUE TITLE
Remove types from report

### ISSUE THREAD

**Issue by flongo** [ariatemplates/at-diff#4]
It would be nice to be able to create a report containing only a set of change types.

**Comment by divdavem** [comment]
It is now possible to configure change types to be included in the report with at-diff 0.0.8, which has just been published to [npm](https://www.npmjs.com/package/at-diff).

The new `filterImpacts` and `filterChanges` options of the grunt task and the `--filter-impacts` and `--filter-changes` of the command line tool are documented in the following pages: [Grunt usage](http://at-diff.ariatemplates.com/grunt.html) and [Command line usage](http://at-diff.ariatemplates.com/cmdline.html)

This feature is implemented in commit ab945d9fff469805d440ffda1add254f17c99885
